//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4338
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dant
    {
        public int ID { get; set; }
        public string CreationDate { get; set; }
        public string OrderTime { get; set; }
        public Nullable<int> ClientCode { get; set; }
        public string Servicee { get; set; }
        public string Statuss { get; set; }
        public string ClosingDate { get; set; }
        public string RentalTime { get; set; }
    }
}
